services:
  - type: web
    name: weather-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENWEATHERMAP_API_KEY
        sync: false
    # Free tier limitations:
    # - Spins down after inactivity (wakes up on first request)
    # - No SSH access
    # - No scaling
    # - No persistent disks
    # - No one-off jobs 